stages:
  kedro_full_pipeline:
    cmd: kedro run
    deps:
      - data/01_raw/games.csv
      - data/01_raw/games_details.csv
      - data/01_raw/teams.csv
      - src/
      - conf/
    outs:
      - data/02_intermediate/
      - data/03_primary/
      - data/04_feature/
      - data/05_model_input/
      - data/06_models/
    metrics:
      - data/08_reporting/