# PARÁMETROS GLOBALES
random_state: 42
test_size: 0.2
cv_folds: 5

# Configuraciones generales
rolling_window: 5
min_games_per_season: 5
outlier_zscore: 4.0

# Columnas críticas que deben existir en games
required_game_cols:
  - GAME_ID
  - SEASON
  - GAME_DATE_EST
  - HOME_TEAM_ID
  - VISITOR_TEAM_ID
  - PTS_home
  - PTS_away
  - HOME_TEAM_WINS

# PARÁMETROS DATA ENGINEERING
data_engineering:
  classification_features:
    - 'PTS_home'
    - 'PTS_away' 
    - 'FG_PCT_home'
    - 'FG_PCT_away'
    - 'FT_PCT_home'
    - 'FT_PCT_away'
    - 'FG3_PCT_home'
    - 'FG3_PCT_away'
    - 'REB_home'
    - 'REB_away'
    - 'AST_home'
    - 'AST_away'
    - 'HOME_HIST_HOME_WIN_PCT'
    - 'AWAY_HIST_AWAY_WIN_PCT'
    - 'WIN_PCT_DIFF'
  regression_features:
    - 'FG_PCT_home'
    - 'FT_PCT_home'
    - 'FG3_PCT_home'
    - 'AST_home'
    - 'REB_home'
    - 'FG_PCT_away'
    - 'FT_PCT_away'
    - 'FG3_PCT_away'
    - 'AST_away'
    - 'REB_away'
    - 'YEAR'
    - 'MONTH'
  classification_target: 'HOME_TEAM_WINS'
  regression_targets:
    local_strength: 'PTS_home'
    away_weakness: 'PTS_away'
    point_differential: 'POINT_DIFFERENTIAL'

# PARÁMETROS MODELOS CLASIFICACIÓN
classification_models:
  logistic_regression:
    model:
      class: sklearn.linear_model.LogisticRegression
      kwargs:
        random_state: 42
        max_iter: 1000
    params:
      C: [0.1, 1.0, 10.0]
      penalty: ['l2']
      solver: ['liblinear']

  random_forest:
    model:
      class: sklearn.ensemble.RandomForestClassifier
      kwargs:
        random_state: 42
    params:
      n_estimators: [100, 200]
      max_depth: [10, 20, null]
      min_samples_split: [2, 5]

  decision_tree:
    model:
      class: sklearn.tree.DecisionTreeClassifier
      kwargs:
        random_state: 42
    params:
      max_depth: [5, 10, 15]
      min_samples_split: [2, 5, 10]

  svm:
    model:
      class: sklearn.svm.SVC
      kwargs:
        random_state: 42
        probability: true
    params:
      C: [0.1, 1.0, 10.0]
      kernel: ['rbf', 'linear']

  naive_bayes:
    model:
      class: sklearn.naive_bayes.GaussianNB
      kwargs: {}

# PARÁMETROS REGRESIÓN
regression:
  features:
    - 'FG_PCT_home'
    - 'FT_PCT_home'
    - 'FG3_PCT_home'
    - 'AST_home'
    - 'REB_home'
    - 'FG_PCT_away'
    - 'FT_PCT_away'
    - 'FG3_PCT_away'
    - 'AST_away'
    - 'REB_away'
    - 'YEAR'
    - 'MONTH'
  targets:
    local_strength: 'PTS_home'
    away_weakness: 'PTS_away'
    point_differential: 'POINT_DIFFERENTIAL'
  team_identifiers:
    - 'HOME_TEAM_ID'
    - 'VISITOR_TEAM_ID'
  sample_size: 10000
  cv_folds: 5
  test_size: 0.2
  random_state: 42
  gridsearch_params:
    random_forest:
      model__n_estimators: [50, 100]
      model__max_depth: [3, 5, None]
    gradient_boosting:
      model__n_estimators: [50, 100]
      model__learning_rate: [0.01, 0.1]
    ridge:
      model__alpha: [0.1, 1.0, 10.0]
    lasso:
      model__alpha: [0.1, 1.0, 10.0]
    elastic_net:
      model__alpha: [0.1, 1.0]
      model__l1_ratio: [0.2, 0.5, 0.8]

# Configuración para manejo de missing values
data_preparation:
  missing_values:
    numeric_strategy: "median"
    categorical_strategy: "most_frequent"

  # Configuración para feature engineering
  feature_engineering:
    min_games_for_stats: 10
    seasons_to_include: [2015, 2016, 2017, 2018, 2019, 2020]

# Configuración union_tablas
union_tablas:
  cols_games_to_drop:
    - 'TEAM_ID_home'
    - 'TEAM_ID_away'
    - 'GAME_STATUS_TEXT'
  cols_teams_to_drop:
    - 'LEAGUE_ID'
    - 'MAX_YEAR'
    - 'MIN_YEAR'
  cols_final_to_drop:
    - 'ABBREVIATION'
    - 'CITY'
  rename_columns:
    visitor_to_away: "AWAY_TEAM_ID"
    away_from: "VISITOR_TEAM_ID"

# PARÁMETROS CLUSTERING
clustering:
  features:
    - "HOME_PTS_MEAN"
    - "HOME_PTS_STD"
    - "HOME_GAMES_COUNT"
    - "HOME_FG_PCT"
    - "HOME_FT_PCT"
    - "HOME_FG3_PCT"
    - "HOME_REB_MEAN"
    - "HOME_AST_MEAN"
    - "HOME_WIN_PCT"
    - "HOME_PT_DIFF_MEAN"
    - "AWAY_PTS_MEAN"
    - "AWAY_PTS_STD"
    - "AWAY_GAMES_COUNT"
    - "AWAY_FG_PCT"
    - "AWAY_FT_PCT"
    - "AWAY_FG3_PCT"
    - "AWAY_REB_MEAN"
    - "AWAY_AST_MEAN"
    - "AWAY_WIN_PCT"
    - "AWAY_PT_DIFF_MEAN"
    - "HOME_ADVANTAGE_PTS"
    - "HOME_ADVANTAGE_WIN"
    - "HOME_ADVANTAGE_REB"
  max_k: 10
  n_clusters: null
  random_state: 42

# PARÁMETROS REDUCCIÓN DE DIMENSIONALIDAD
dimensionality_reduction:
  pca_n_components: 10
  tsne_n_components: 2
  tsne_perplexity: 30
  umap_n_components: 2
  umap_n_neighbors: 15
  umap_min_dist: 0.1
  random_state: 42

# PARÁMETROS DETECCIÓN DE ANOMALÍAS
anomaly_detection:
  contamination: 0.1
  n_estimators: 100
  n_neighbors: 20
  kernel: "rbf"
  random_state: 42

# PARÁMETROS REGLAS DE ASOCIACIÓN (OPCIONAL)
association_rules:
  min_support: 0.01
  min_confidence: 0.5
  min_lift: 1.0
  max_length: 3

# PARÁMETROS VISUALIZACIÓN
visualization:
  figure_size: [12, 8]
  color_palette: "viridis"
  style: "whitegrid"
  dpi: 300

# PARÁMETROS EVALUACIÓN DE MODELOS
model_evaluation:
  classification_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  regression_metrics:
    - "r2"
    - "mae"
    - "mse"
    - "rmse"
  clustering_metrics:
    - "silhouette_score"
    - "calinski_harabasz_score"
    - "davies_bouldin_score"

# PARÁMETROS OPTIMIZACIÓN
optimization:
  n_trials: 100
  timeout: 3600
  direction: "maximize"

# PARÁMETROS DESPLIEGUE
deployment:
  model_format: "pickle"
  api_timeout: 30
  batch_size: 1000
  monitoring_window: 10000